#spring.application.name=Bienes-raices
#server.port=8080
#spring.datasource.url=jdbc:mysql://localhost:3307/bienesraices_crud?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
#spring.datasource.username=root
#spring.datasource.password=chara3130
#spring.data.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:mysql://localhost:3307/bienesraices_crud?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=chara3130
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true

logging.pattern.dateformat=HH:mm
#con este se apaga cosas o informacion que no se debe enviar
spring.main.banner-mode=off
spring.thymeleaf.cache=false

#conexion mysql
spring.datasource.url=jdbc:mysql://localhost:3307/bienesraices_crud?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=chara3130
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#Mostrar sql
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.hibernate.ddl-auto=update
#update mantienes los datos en la base de datos
#spring.jpa.hibernate.ddl-auto=create  / borra los datos que se sube en la base de datos



logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Ajustamos a 10MB para que el controlador pueda recibir el archivo y mostrar el error de "Formato no válido"
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

